forage.ollama.agent.model.kind=ollama
forage.ollama.agent.model.name=granite4:3b
forage.ollama.agent.base.url=http://localhost:11434

#RAG

forage.ollama.agent.embedding.model.name=nomic-embed-text
forage.ollama.agent.embedding.model.base.url=http://localhost:11434
forage.ollama.agent.embedding.model.timeout=PT30S
forage.ollama.agent.in.memory.store.file.source=company-knowledge-base.txt
forage.ollama.agent.in.memory.store.max.size=300
forage.ollama.agent.in.memory.store.overlap.size=100

forage.ollama.agent.rag.max.results=3
forage.ollama.agent.rag.min.score=0.6
